project:
  type: website
  output-dir: ../docs

website:
  title: "Me"
  sidebar: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - music.qmd
      - projects.qmd


format:
  html:
    theme: styles.scss
    toc: false
    include-after-body: js/home.html



