project:
  type: website
  output-dir: ../docs

website:
  title: "Me"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - music.qmd
      - projects.qmd


format:
  html:
    theme: superhero
    css: styles.css
    toc: true
    include-after-body: js/home.html



