project:
  type: website
  output-dir: ../docs

website:
  title: "Me"
  sidebar: false
  navbar:
    logo: assets/northpolepanic_logo_square.png
    logo-href: /index.html
    title: false
    search: false
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - music.qmd
      - projects.qmd



format:
  html:
    theme: styles.scss
    toc: false
    include-after-body: js/home.html



